<?php
  
  $padSyntaxUnknowTag   = '?!?';    //  *error* / *print* / *empty* /...
  $padSyntaxUnknowVar   = '!!!';    //  *error* / *print* / *empty* /...
  $padSyntaxUnknowClose = '???';    //  *error* / *print* / *empty* /...

?>