/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 4
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_text = 2,
  sym_comment = 3,
  sym_construct = 4,
  anon_sym_ignore = 5,
  anon_sym_SLASH = 6,
  anon_sym_LBRACE = 7,
  anon_sym_TILDE = 8,
  anon_sym_TILDE2 = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  aux_sym_tag_name_token1 = 12,
  anon_sym_AT = 13,
  aux_sym_tag_name_token2 = 14,
  anon_sym_COMMA = 15,
  anon_sym_EQ = 16,
  anon_sym_COLON2 = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_PIPE = 22,
  sym_placeholder = 23,
  sym_variable = 24,
  sym_string = 25,
  sym_number = 26,
  sym_format = 27,
  sym_operator = 28,
  sym__block_start = 29,
  sym__block_end = 30,
  sym_raw_text = 31,
  sym__error_sentinel = 32,
  sym_template = 33,
  sym__node = 34,
  sym_block = 35,
  sym_body = 36,
  sym_ignore_block = 37,
  sym__ignore_open_tag = 38,
  sym__ignore_name = 39,
  sym_tag = 40,
  sym_open_tag = 41,
  sym_close_tag = 42,
  sym_field_tag = 43,
  sym__open = 44,
  sym__close = 45,
  sym_tag_name = 46,
  sym_arguments = 47,
  sym__argument = 48,
  sym_option = 49,
  sym_pipe = 50,
  sym_prefixed_name = 51,
  sym_property_reference = 52,
  aux_sym_template_repeat1 = 53,
  aux_sym_arguments_repeat1 = 54,
  alias_sym_function_name = 55,
  alias_sym_option_name = 56,
  alias_sym_prefix = 57,
  alias_sym_property = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_text] = "text",
  [sym_comment] = "comment",
  [sym_construct] = "construct",
  [anon_sym_ignore] = "identifier",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_TILDE] = "~",
  [anon_sym_TILDE2] = "~",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_tag_name_token1] = "identifier",
  [anon_sym_AT] = "@",
  [aux_sym_tag_name_token2] = "identifier",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON2] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PIPE] = "|",
  [sym_placeholder] = "placeholder",
  [sym_variable] = "variable",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_format] = "format",
  [sym_operator] = "operator",
  [sym__block_start] = "_block_start",
  [sym__block_end] = "_block_end",
  [sym_raw_text] = "raw_text",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_block] = "block",
  [sym_body] = "body",
  [sym_ignore_block] = "ignore_block",
  [sym__ignore_open_tag] = "open_tag",
  [sym__ignore_name] = "tag_name",
  [sym_tag] = "tag",
  [sym_open_tag] = "open_tag",
  [sym_close_tag] = "close_tag",
  [sym_field_tag] = "field_tag",
  [sym__open] = "_open",
  [sym__close] = "_close",
  [sym_tag_name] = "tag_name",
  [sym_arguments] = "arguments",
  [sym__argument] = "_argument",
  [sym_option] = "option",
  [sym_pipe] = "pipe",
  [sym_prefixed_name] = "prefixed_name",
  [sym_property_reference] = "property_reference",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [alias_sym_function_name] = "function_name",
  [alias_sym_option_name] = "option_name",
  [alias_sym_prefix] = "prefix",
  [alias_sym_property] = "property",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_text] = sym_text,
  [sym_comment] = sym_comment,
  [sym_construct] = sym_construct,
  [anon_sym_ignore] = sym_identifier,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_TILDE2] = anon_sym_TILDE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_tag_name_token1] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_tag_name_token2] = sym_identifier,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON2] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_placeholder] = sym_placeholder,
  [sym_variable] = sym_variable,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_format] = sym_format,
  [sym_operator] = sym_operator,
  [sym__block_start] = sym__block_start,
  [sym__block_end] = sym__block_end,
  [sym_raw_text] = sym_raw_text,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_block] = sym_block,
  [sym_body] = sym_body,
  [sym_ignore_block] = sym_ignore_block,
  [sym__ignore_open_tag] = sym_open_tag,
  [sym__ignore_name] = sym_tag_name,
  [sym_tag] = sym_tag,
  [sym_open_tag] = sym_open_tag,
  [sym_close_tag] = sym_close_tag,
  [sym_field_tag] = sym_field_tag,
  [sym__open] = sym__open,
  [sym__close] = sym__close,
  [sym_tag_name] = sym_tag_name,
  [sym_arguments] = sym_arguments,
  [sym__argument] = sym__argument,
  [sym_option] = sym_option,
  [sym_pipe] = sym_pipe,
  [sym_prefixed_name] = sym_prefixed_name,
  [sym_property_reference] = sym_property_reference,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [alias_sym_function_name] = alias_sym_function_name,
  [alias_sym_option_name] = alias_sym_option_name,
  [alias_sym_prefix] = alias_sym_prefix,
  [alias_sym_property] = alias_sym_property,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_construct] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ignore] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__block_start] = {
    .visible = false,
    .named = true,
  },
  [sym__block_end] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_ignore_block] = {
    .visible = true,
    .named = true,
  },
  [sym__ignore_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__ignore_name] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_field_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__open] = {
    .visible = false,
    .named = true,
  },
  [sym__close] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_prefixed_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_property] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_name = 2,
  field_prefix = 3,
  field_property = 4,
  field_target = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_name] = "name",
  [field_prefix] = "prefix",
  [field_property] = "property",
  [field_target] = "target",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 0, .length = 1},
  [6] = {.index = 4, .length = 2},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_property, 0},
  [2] =
    {field_name, 1, .inherited = true},
  [3] =
    {field_function, 1},
  [4] =
    {field_name, 2},
    {field_prefix, 0},
  [6] =
    {field_property, 0},
    {field_target, 2},
  [8] =
    {field_name, 0},
    {field_value, 2},
  [10] =
    {field_function, 3},
    {field_prefix, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = alias_sym_property,
  },
  [4] = {
    [1] = alias_sym_function_name,
  },
  [5] = {
    [0] = alias_sym_option_name,
  },
  [6] = {
    [0] = alias_sym_prefix,
  },
  [7] = {
    [0] = alias_sym_property,
  },
  [8] = {
    [0] = alias_sym_option_name,
  },
  [9] = {
    [1] = alias_sym_prefix,
    [3] = alias_sym_function_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 3,
  [9] = 7,
  [10] = 2,
  [11] = 3,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 27,
  [39] = 31,
  [40] = 28,
  [41] = 41,
  [42] = 29,
  [43] = 43,
  [44] = 30,
  [45] = 28,
  [46] = 41,
  [47] = 43,
  [48] = 48,
  [49] = 29,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 48,
  [55] = 31,
  [56] = 30,
  [57] = 50,
  [58] = 51,
  [59] = 59,
  [60] = 27,
  [61] = 52,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 63,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 70,
  [74] = 74,
  [75] = 75,
  [76] = 71,
  [77] = 69,
  [78] = 75,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 74,
  [83] = 71,
  [84] = 84,
  [85] = 79,
  [86] = 86,
  [87] = 74,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 31,
  [92] = 90,
  [93] = 88,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 98,
  [100] = 100,
  [101] = 101,
  [102] = 98,
  [103] = 103,
  [104] = 104,
  [105] = 98,
  [106] = 106,
  [107] = 103,
  [108] = 108,
  [109] = 104,
  [110] = 108,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, ' '}, {'"', '"'}, {'\'', '.'}, {'0', '>'}, {'@', '@'}, {'[', ']'}, {'`', '`'}, {'{', '}'},
  {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(62);
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '.', 107,
        '/', 68,
        ':', 75,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 77,
        '[', 86,
        ']', 87,
        '{', 70,
        '|', 88,
        '}', 74,
        '~', 72,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '-', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '-', 110,
        '.', 107,
        ':', 83,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 89,
        '[', 86,
        ']', 87,
        '{', 69,
        '|', 88,
        '}', 74,
        '~', 73,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '/', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '.', 107,
        ':', 75,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 77,
        '[', 86,
        ']', 87,
        '{', 69,
        '|', 88,
        '}', 74,
        '~', 73,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '-', 102,
        '/', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '.', 107,
        ':', 75,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 89,
        '[', 86,
        ']', 87,
        '{', 69,
        '|', 88,
        '}', 74,
        '~', 73,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '-', 102,
        '/', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '.', 107,
        ':', 83,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 89,
        '[', 86,
        ']', 87,
        '{', 69,
        '|', 88,
        '}', 74,
        '~', 73,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '-', 102,
        '/', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(98);
      if (lookahead == '\\') ADVANCE(57);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '#', 6,
        '\'', 59,
        '-', 16,
        '.', 50,
        '0', 90,
        ' ', 17,
        '+', 17,
        '*', 93,
        '<', 93,
        '>', 93,
      );
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '|' &&
          lookahead != '}') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '|' &&
          lookahead != '}') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(7);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '$', 14,
        '/', 68,
        '~', 72,
        '!', 18,
        '#', 18,
        '%', 18,
        '&', 18,
        '?', 18,
        '^', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 13:
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == '/') ADVANCE(68);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 14:
      ADVANCE_MAP(
        '$', 91,
        '-', 48,
        '*', 93,
        '<', 93,
        '>', 93,
        '!', 18,
        '#', 18,
        '%', 18,
        '&', 18,
        '?', 18,
        '^', 18,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 15:
      if (lookahead == '\'') ADVANCE(98);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == '0') ADVANCE(90);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 17:
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == '0') ADVANCE(17);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '*' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(20);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(47);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '-') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 25:
      if (lookahead == '-') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 27:
      if (lookahead == '@') ADVANCE(67);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 45:
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 46:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 47:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 56:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 58:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 59:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 60:
      if (eof) ADVANCE(62);
      ADVANCE_MAP(
        '!', 105,
        '"', 5,
        '#', 18,
        '$', 14,
        '%', 103,
        '&', 104,
        '\'', 15,
        '(', 84,
        ')', 85,
        ',', 81,
        '.', 107,
        '/', 68,
        ':', 83,
        '<', 109,
        '=', 82,
        '>', 108,
        '@', 89,
        '[', 86,
        ']', 87,
        '{', 70,
        '|', 88,
        '}', 74,
        '~', 73,
        '?', 106,
        '^', 106,
        '*', 102,
        '+', 102,
        '-', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 61:
      if (eof) ADVANCE(62);
      if (lookahead == '@') ADVANCE(64);
      if (lookahead == '{') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(61);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(39);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'p') ADVANCE(28);
      if (lookahead == 's') ADVANCE(43);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_construct);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '-') ADVANCE(22);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(63);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_TILDE2);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_tag_name_token2);
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_tag_name_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_tag_name_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(102);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_COLON2);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_placeholder);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_variable);
      ADVANCE_MAP(
        '\'', 59,
        '.', 54,
        '0', 90,
        ':', 49,
        '@', 24,
        ' ', 17,
        '#', 17,
        '+', 17,
        '-', 17,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '*' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(54);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '@') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_format);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_operator);
      ADVANCE_MAP(
        '#', 6,
        '\'', 59,
        '-', 16,
        '.', 50,
        '0', 90,
        ' ', 17,
        '+', 17,
        '*', 93,
        '<', 93,
        '>', 93,
      );
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'u' ||
          lookahead == 'x') ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '&') ADVANCE(106);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '*' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '%') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '=') ADVANCE(102);
      if (lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '*' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '?' ||
          lookahead == '^') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '.') ADVANCE(102);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(102);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(102);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'i') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'g') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_ignore);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 61, .external_lex_state = 2},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 61, .external_lex_state = 3},
  [33] = {.lex_state = 61, .external_lex_state = 3},
  [34] = {.lex_state = 61, .external_lex_state = 3},
  [35] = {.lex_state = 61, .external_lex_state = 2},
  [36] = {.lex_state = 61, .external_lex_state = 2},
  [37] = {.lex_state = 61, .external_lex_state = 3},
  [38] = {.lex_state = 61, .external_lex_state = 3},
  [39] = {.lex_state = 61, .external_lex_state = 2},
  [40] = {.lex_state = 61, .external_lex_state = 2},
  [41] = {.lex_state = 61, .external_lex_state = 2},
  [42] = {.lex_state = 61, .external_lex_state = 2},
  [43] = {.lex_state = 61, .external_lex_state = 2},
  [44] = {.lex_state = 61, .external_lex_state = 3},
  [45] = {.lex_state = 61, .external_lex_state = 3},
  [46] = {.lex_state = 61, .external_lex_state = 3},
  [47] = {.lex_state = 61, .external_lex_state = 3},
  [48] = {.lex_state = 61, .external_lex_state = 3},
  [49] = {.lex_state = 61, .external_lex_state = 3},
  [50] = {.lex_state = 61, .external_lex_state = 3},
  [51] = {.lex_state = 61, .external_lex_state = 3},
  [52] = {.lex_state = 61, .external_lex_state = 3},
  [53] = {.lex_state = 61, .external_lex_state = 3},
  [54] = {.lex_state = 61, .external_lex_state = 2},
  [55] = {.lex_state = 61, .external_lex_state = 3},
  [56] = {.lex_state = 61, .external_lex_state = 2},
  [57] = {.lex_state = 61, .external_lex_state = 2},
  [58] = {.lex_state = 61, .external_lex_state = 2},
  [59] = {.lex_state = 61, .external_lex_state = 3},
  [60] = {.lex_state = 61, .external_lex_state = 2},
  [61] = {.lex_state = 61, .external_lex_state = 2},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 12},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 25},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 56},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 56},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0, .external_lex_state = 5},
  [104] = {.lex_state = 12},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 12},
  [107] = {.lex_state = 0, .external_lex_state = 5},
  [108] = {.lex_state = 0, .external_lex_state = 5},
  [109] = {.lex_state = 12},
  [110] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_ignore] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_TILDE2] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_placeholder] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_format] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym__block_start] = ACTIONS(1),
    [sym__block_end] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(101),
    [sym__node] = STATE(36),
    [sym_block] = STATE(36),
    [sym_ignore_block] = STATE(36),
    [sym_tag] = STATE(36),
    [sym_close_tag] = STATE(36),
    [sym_field_tag] = STATE(36),
    [sym__open] = STATE(66),
    [aux_sym_template_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_construct] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym__block_start] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(28),
    [sym_arguments] = STATE(83),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(60),
    [sym_arguments] = STATE(74),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(53),
    [sym_arguments] = STATE(86),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(40),
    [sym_arguments] = STATE(76),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(6)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(89),
    [sym_arguments] = STATE(84),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(7)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(54),
    [sym_arguments] = STATE(70),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(8)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(38),
    [sym_arguments] = STATE(87),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(9)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(48),
    [sym_arguments] = STATE(73),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(10)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(45),
    [sym_arguments] = STATE(71),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
  [STATE(11)] = {
    [sym_tag] = STATE(12),
    [sym_field_tag] = STATE(12),
    [sym__open] = STATE(72),
    [sym__close] = STATE(27),
    [sym_arguments] = STATE(82),
    [sym__argument] = STATE(12),
    [sym_option] = STATE(12),
    [sym_pipe] = STATE(12),
    [sym_prefixed_name] = STATE(12),
    [sym_property_reference] = STATE(12),
    [aux_sym_arguments_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_TILDE2] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_COLON2] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(25),
    [sym_placeholder] = ACTIONS(21),
    [sym_variable] = ACTIONS(23),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_format] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_PIPE,
    STATE(72), 1,
      sym__open,
    ACTIONS(51), 2,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
    ACTIONS(55), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    STATE(13), 8,
      sym_tag,
      sym_field_tag,
      sym__argument,
      sym_option,
      sym_pipe,
      sym_prefixed_name,
      sym_property_reference,
      aux_sym_arguments_repeat1,
    ACTIONS(53), 10,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
  [44] = 8,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      anon_sym_PIPE,
    STATE(72), 1,
      sym__open,
    ACTIONS(63), 2,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
    ACTIONS(68), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    STATE(13), 8,
      sym_tag,
      sym_field_tag,
      sym__argument,
      sym_option,
      sym_pipe,
      sym_prefixed_name,
      sym_property_reference,
      aux_sym_arguments_repeat1,
    ACTIONS(65), 10,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
  [88] = 4,
    ACTIONS(76), 1,
      anon_sym_COLON,
    ACTIONS(78), 1,
      anon_sym_AT,
    ACTIONS(80), 5,
      anon_sym_EQ,
      anon_sym_COLON2,
      sym_placeholder,
      sym_variable,
      sym_operator,
    ACTIONS(74), 13,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [117] = 5,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      anon_sym_AT,
    ACTIONS(88), 1,
      anon_sym_EQ,
    ACTIONS(90), 4,
      anon_sym_COLON2,
      sym_placeholder,
      sym_variable,
      sym_operator,
    ACTIONS(82), 13,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [148] = 7,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(98), 1,
      sym_variable,
    STATE(24), 1,
      sym_field_tag,
    STATE(106), 1,
      sym__open,
    ACTIONS(96), 2,
      anon_sym_EQ,
      sym_operator,
    ACTIONS(92), 3,
      sym_string,
      sym_number,
      sym_identifier,
    ACTIONS(94), 11,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_format,
  [183] = 3,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(104), 4,
      anon_sym_EQ,
      anon_sym_COLON2,
      sym_variable,
      sym_operator,
    ACTIONS(100), 14,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [209] = 3,
    ACTIONS(110), 1,
      aux_sym_tag_name_token2,
    ACTIONS(106), 5,
      anon_sym_EQ,
      sym_variable,
      sym_number,
      sym_operator,
      sym_identifier,
    ACTIONS(108), 13,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_format,
  [235] = 2,
    ACTIONS(114), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(112), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [258] = 2,
    ACTIONS(118), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(116), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [281] = 2,
    ACTIONS(122), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(120), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [304] = 2,
    ACTIONS(126), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(124), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [327] = 2,
    ACTIONS(130), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(128), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [350] = 2,
    ACTIONS(134), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(132), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [373] = 2,
    ACTIONS(138), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(136), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [396] = 3,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(144), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(142), 14,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
  [421] = 2,
    ACTIONS(148), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(146), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [444] = 2,
    ACTIONS(152), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(150), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [467] = 2,
    ACTIONS(156), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(154), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [490] = 2,
    ACTIONS(160), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(158), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [513] = 2,
    ACTIONS(164), 3,
      anon_sym_EQ,
      sym_variable,
      sym_operator,
    ACTIONS(162), 15,
      anon_sym_LBRACE,
      anon_sym_TILDE2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PIPE,
      sym_placeholder,
      sym_string,
      sym_number,
      sym_format,
      sym_identifier,
  [536] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      sym_text,
    ACTIONS(170), 1,
      sym__block_start,
    ACTIONS(172), 1,
      sym__block_end,
    STATE(67), 1,
      sym__open,
    STATE(110), 1,
      sym_body,
    ACTIONS(168), 2,
      sym_comment,
      sym_construct,
    STATE(34), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [568] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      sym_text,
    ACTIONS(170), 1,
      sym__block_start,
    ACTIONS(174), 1,
      sym__block_end,
    STATE(67), 1,
      sym__open,
    STATE(108), 1,
      sym_body,
    ACTIONS(168), 2,
      sym_comment,
      sym_construct,
    STATE(34), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [600] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 1,
      sym__block_start,
    ACTIONS(176), 1,
      sym_text,
    ACTIONS(180), 1,
      sym__block_end,
    STATE(67), 1,
      sym__open,
    ACTIONS(178), 2,
      sym_comment,
      sym_construct,
    STATE(37), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [629] = 7,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 1,
      sym_text,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      sym__block_start,
    STATE(66), 1,
      sym__open,
    ACTIONS(187), 2,
      sym_comment,
      sym_construct,
    STATE(35), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [658] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym__block_start,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 1,
      sym_text,
    STATE(66), 1,
      sym__open,
    ACTIONS(200), 2,
      sym_comment,
      sym_construct,
    STATE(35), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [687] = 7,
    ACTIONS(182), 1,
      sym__block_end,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(202), 1,
      sym_text,
    ACTIONS(208), 1,
      sym__block_start,
    STATE(67), 1,
      sym__open,
    ACTIONS(205), 2,
      sym_comment,
      sym_construct,
    STATE(37), 7,
      sym__node,
      sym_block,
      sym_ignore_block,
      sym_tag,
      sym_close_tag,
      sym_field_tag,
      aux_sym_template_repeat1,
  [716] = 2,
    ACTIONS(148), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(146), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [727] = 2,
    ACTIONS(164), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(162), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [738] = 2,
    ACTIONS(152), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(150), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [749] = 2,
    ACTIONS(213), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(211), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [760] = 2,
    ACTIONS(156), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(154), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [771] = 2,
    ACTIONS(217), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(215), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [782] = 2,
    ACTIONS(160), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(158), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [793] = 2,
    ACTIONS(152), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(150), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [804] = 2,
    ACTIONS(213), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(211), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [815] = 2,
    ACTIONS(217), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(215), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [826] = 2,
    ACTIONS(219), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(221), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [837] = 2,
    ACTIONS(156), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(154), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [848] = 2,
    ACTIONS(223), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(225), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [859] = 2,
    ACTIONS(227), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(229), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [870] = 2,
    ACTIONS(231), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(233), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [881] = 2,
    ACTIONS(235), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(237), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [892] = 2,
    ACTIONS(219), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(221), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [903] = 2,
    ACTIONS(164), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(162), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [914] = 2,
    ACTIONS(160), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(158), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [925] = 2,
    ACTIONS(223), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(225), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [936] = 2,
    ACTIONS(227), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(229), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [947] = 2,
    ACTIONS(239), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(241), 4,
      sym__block_start,
      sym__block_end,
      sym_comment,
      sym_construct,
  [958] = 2,
    ACTIONS(148), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(146), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [969] = 2,
    ACTIONS(231), 2,
      sym_text,
      anon_sym_LBRACE,
    ACTIONS(233), 4,
      sym__block_start,
      ts_builtin_sym_end,
      sym_comment,
      sym_construct,
  [980] = 3,
    ACTIONS(247), 1,
      anon_sym_TILDE,
    ACTIONS(243), 2,
      anon_sym_ignore,
      sym_identifier,
    ACTIONS(245), 2,
      anon_sym_SLASH,
      sym_variable,
  [992] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_open_tag,
    STATE(65), 1,
      sym__open,
    STATE(90), 1,
      sym__ignore_open_tag,
  [1005] = 2,
    ACTIONS(249), 2,
      anon_sym_ignore,
      sym_identifier,
    ACTIONS(251), 2,
      anon_sym_SLASH,
      sym_variable,
  [1014] = 4,
    ACTIONS(253), 1,
      sym_identifier,
    ACTIONS(255), 1,
      anon_sym_ignore,
    STATE(4), 1,
      sym_tag_name,
    STATE(6), 1,
      sym__ignore_name,
  [1027] = 4,
    ACTIONS(257), 1,
      sym_identifier,
    ACTIONS(259), 1,
      anon_sym_SLASH,
    ACTIONS(261), 1,
      sym_variable,
    STATE(5), 1,
      sym_tag_name,
  [1040] = 4,
    ACTIONS(257), 1,
      sym_identifier,
    ACTIONS(263), 1,
      anon_sym_SLASH,
    ACTIONS(265), 1,
      sym_variable,
    STATE(10), 1,
      sym_tag_name,
  [1053] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_open_tag,
    STATE(65), 1,
      sym__open,
    STATE(92), 1,
      sym__ignore_open_tag,
  [1066] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_close_tag,
    STATE(109), 1,
      sym__open,
  [1076] = 3,
    ACTIONS(27), 1,
      anon_sym_TILDE2,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym__close,
  [1086] = 3,
    ACTIONS(31), 1,
      anon_sym_TILDE2,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym__close,
  [1096] = 3,
    ACTIONS(257), 1,
      sym_identifier,
    ACTIONS(271), 1,
      sym_variable,
    STATE(2), 1,
      sym_tag_name,
  [1106] = 3,
    ACTIONS(31), 1,
      anon_sym_TILDE2,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym__close,
  [1116] = 3,
    ACTIONS(27), 1,
      anon_sym_TILDE2,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym__close,
  [1126] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_close_tag,
    STATE(104), 1,
      sym__open,
  [1136] = 3,
    ACTIONS(27), 1,
      anon_sym_TILDE2,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym__close,
  [1146] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym_close_tag,
    STATE(104), 1,
      sym__open,
  [1156] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_close_tag,
    STATE(109), 1,
      sym__open,
  [1166] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_close_tag,
    STATE(109), 1,
      sym__open,
  [1176] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_close_tag,
    STATE(104), 1,
      sym__open,
  [1186] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_close_tag,
    STATE(109), 1,
      sym__open,
  [1196] = 3,
    ACTIONS(17), 1,
      anon_sym_TILDE2,
    ACTIONS(279), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym__close,
  [1206] = 3,
    ACTIONS(17), 1,
      anon_sym_TILDE2,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym__close,
  [1216] = 3,
    ACTIONS(37), 1,
      anon_sym_TILDE2,
    ACTIONS(283), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym__close,
  [1226] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_close_tag,
    STATE(104), 1,
      sym__open,
  [1236] = 3,
    ACTIONS(31), 1,
      anon_sym_TILDE2,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      sym__close,
  [1246] = 3,
    ACTIONS(31), 1,
      anon_sym_TILDE2,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym__close,
  [1256] = 2,
    ACTIONS(257), 1,
      sym_identifier,
    STATE(7), 1,
      sym_tag_name,
  [1263] = 1,
    ACTIONS(289), 2,
      sym__block_end,
      sym_raw_text,
  [1268] = 2,
    ACTIONS(291), 1,
      sym__block_end,
    ACTIONS(293), 1,
      sym_raw_text,
  [1275] = 1,
    ACTIONS(162), 2,
      sym__block_end,
      sym_raw_text,
  [1280] = 2,
    ACTIONS(295), 1,
      sym__block_end,
    ACTIONS(297), 1,
      sym_raw_text,
  [1287] = 2,
    ACTIONS(257), 1,
      sym_identifier,
    STATE(9), 1,
      sym_tag_name,
  [1294] = 1,
    ACTIONS(299), 2,
      sym__block_end,
      sym_raw_text,
  [1299] = 1,
    ACTIONS(301), 1,
      aux_sym_tag_name_token2,
  [1303] = 1,
    ACTIONS(303), 1,
      sym_identifier,
  [1307] = 1,
    ACTIONS(305), 1,
      aux_sym_tag_name_token1,
  [1311] = 1,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
  [1315] = 1,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
  [1319] = 1,
    ACTIONS(311), 1,
      aux_sym_tag_name_token1,
  [1323] = 1,
    ACTIONS(313), 1,
      ts_builtin_sym_end,
  [1327] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
  [1331] = 1,
    ACTIONS(317), 1,
      sym__block_end,
  [1335] = 1,
    ACTIONS(259), 1,
      anon_sym_SLASH,
  [1339] = 1,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
  [1343] = 1,
    ACTIONS(271), 1,
      sym_variable,
  [1347] = 1,
    ACTIONS(321), 1,
      sym__block_end,
  [1351] = 1,
    ACTIONS(323), 1,
      sym__block_end,
  [1355] = 1,
    ACTIONS(263), 1,
      anon_sym_SLASH,
  [1359] = 1,
    ACTIONS(325), 1,
      sym__block_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 44,
  [SMALL_STATE(14)] = 88,
  [SMALL_STATE(15)] = 117,
  [SMALL_STATE(16)] = 148,
  [SMALL_STATE(17)] = 183,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 235,
  [SMALL_STATE(20)] = 258,
  [SMALL_STATE(21)] = 281,
  [SMALL_STATE(22)] = 304,
  [SMALL_STATE(23)] = 327,
  [SMALL_STATE(24)] = 350,
  [SMALL_STATE(25)] = 373,
  [SMALL_STATE(26)] = 396,
  [SMALL_STATE(27)] = 421,
  [SMALL_STATE(28)] = 444,
  [SMALL_STATE(29)] = 467,
  [SMALL_STATE(30)] = 490,
  [SMALL_STATE(31)] = 513,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 568,
  [SMALL_STATE(34)] = 600,
  [SMALL_STATE(35)] = 629,
  [SMALL_STATE(36)] = 658,
  [SMALL_STATE(37)] = 687,
  [SMALL_STATE(38)] = 716,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 738,
  [SMALL_STATE(41)] = 749,
  [SMALL_STATE(42)] = 760,
  [SMALL_STATE(43)] = 771,
  [SMALL_STATE(44)] = 782,
  [SMALL_STATE(45)] = 793,
  [SMALL_STATE(46)] = 804,
  [SMALL_STATE(47)] = 815,
  [SMALL_STATE(48)] = 826,
  [SMALL_STATE(49)] = 837,
  [SMALL_STATE(50)] = 848,
  [SMALL_STATE(51)] = 859,
  [SMALL_STATE(52)] = 870,
  [SMALL_STATE(53)] = 881,
  [SMALL_STATE(54)] = 892,
  [SMALL_STATE(55)] = 903,
  [SMALL_STATE(56)] = 914,
  [SMALL_STATE(57)] = 925,
  [SMALL_STATE(58)] = 936,
  [SMALL_STATE(59)] = 947,
  [SMALL_STATE(60)] = 958,
  [SMALL_STATE(61)] = 969,
  [SMALL_STATE(62)] = 980,
  [SMALL_STATE(63)] = 992,
  [SMALL_STATE(64)] = 1005,
  [SMALL_STATE(65)] = 1014,
  [SMALL_STATE(66)] = 1027,
  [SMALL_STATE(67)] = 1040,
  [SMALL_STATE(68)] = 1053,
  [SMALL_STATE(69)] = 1066,
  [SMALL_STATE(70)] = 1076,
  [SMALL_STATE(71)] = 1086,
  [SMALL_STATE(72)] = 1096,
  [SMALL_STATE(73)] = 1106,
  [SMALL_STATE(74)] = 1116,
  [SMALL_STATE(75)] = 1126,
  [SMALL_STATE(76)] = 1136,
  [SMALL_STATE(77)] = 1146,
  [SMALL_STATE(78)] = 1156,
  [SMALL_STATE(79)] = 1166,
  [SMALL_STATE(80)] = 1176,
  [SMALL_STATE(81)] = 1186,
  [SMALL_STATE(82)] = 1196,
  [SMALL_STATE(83)] = 1206,
  [SMALL_STATE(84)] = 1216,
  [SMALL_STATE(85)] = 1226,
  [SMALL_STATE(86)] = 1236,
  [SMALL_STATE(87)] = 1246,
  [SMALL_STATE(88)] = 1256,
  [SMALL_STATE(89)] = 1263,
  [SMALL_STATE(90)] = 1268,
  [SMALL_STATE(91)] = 1275,
  [SMALL_STATE(92)] = 1280,
  [SMALL_STATE(93)] = 1287,
  [SMALL_STATE(94)] = 1294,
  [SMALL_STATE(95)] = 1299,
  [SMALL_STATE(96)] = 1303,
  [SMALL_STATE(97)] = 1307,
  [SMALL_STATE(98)] = 1311,
  [SMALL_STATE(99)] = 1315,
  [SMALL_STATE(100)] = 1319,
  [SMALL_STATE(101)] = 1323,
  [SMALL_STATE(102)] = 1327,
  [SMALL_STATE(103)] = 1331,
  [SMALL_STATE(104)] = 1335,
  [SMALL_STATE(105)] = 1339,
  [SMALL_STATE(106)] = 1343,
  [SMALL_STATE(107)] = 1347,
  [SMALL_STATE(108)] = 1351,
  [SMALL_STATE(109)] = 1355,
  [SMALL_STATE(110)] = 1359,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 1, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 2, 0, 5),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 2, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 2, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 2, 0, 4),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 2, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 2, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 3, 0, 6),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 3, 0, 6),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ignore_name, 1, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__ignore_name, 1, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_reference, 3, 0, 7),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_reference, 3, 0, 7),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 3, 0, 7),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 3, 0, 7),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefixed_name, 3, 0, 6),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefixed_name, 3, 0, 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 8),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 3, 0, 8),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 4, 0, 9),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 4, 0, 9),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_tag, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_tag, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_tag, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_tag, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__close, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__close, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_block, 4, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignore_block, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignore_block, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_block, 5, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 5, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 5, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_tag, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 4, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_tag, 4, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__open, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__open, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ignore_open_tag, 3, 0, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ignore_open_tag, 4, 0, 3),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [313] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__block_start = 0,
  ts_external_token__block_end = 1,
  ts_external_token_raw_text = 2,
  ts_external_token__error_sentinel = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__block_start] = sym__block_start,
  [ts_external_token__block_end] = sym__block_end,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__block_start] = true,
    [ts_external_token__block_end] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__block_start] = true,
  },
  [3] = {
    [ts_external_token__block_start] = true,
    [ts_external_token__block_end] = true,
  },
  [4] = {
    [ts_external_token__block_end] = true,
    [ts_external_token_raw_text] = true,
  },
  [5] = {
    [ts_external_token__block_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_pad_external_scanner_create(void);
void tree_sitter_pad_external_scanner_destroy(void *);
bool tree_sitter_pad_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_pad_external_scanner_serialize(void *, char *);
void tree_sitter_pad_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pad(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_pad_external_scanner_create,
      tree_sitter_pad_external_scanner_destroy,
      tree_sitter_pad_external_scanner_scan,
      tree_sitter_pad_external_scanner_serialize,
      tree_sitter_pad_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
