# Income per person (dollars), life expectancy (years), population (millions)
- country: Netherlands
  continent: Europe
  income: 57000
  life: 81.7
  people: 17.9
- country: Germany
  continent: Europe
  income: 53000
  life: 80.9
  people: 84.5
- country: Poland
  continent: Europe
  income: 37000
  life: 77.4
  people: 37.6
- country: Brazil
  continent: Americas
  income: 15000
  life: 75.8
  people: 216.4
- country: United States
  continent: Americas
  income: 65000
  life: 77.5
  people: 335.0
- country: Mexico
  continent: Americas
  income: 19000
  life: 75.0
  people: 128.5
- country: India
  continent: Asia
  income: 7000
  life: 70.8
  people: 1428.6
- country: Japan
  continent: Asia
  income: 42000
  life: 84.5
  people: 123.3
- country: Indonesia
  continent: Asia
  income: 12000
  life: 71.7
  people: 277.5
