# Speakers in millions, first and second language together
- language: English
  speakers: 1515
- language: Mandarin Chinese
  speakers: 1140
- language: Hindi
  speakers: 609
- language: Spanish
  speakers: 560
- language: Standard Arabic
  speakers: 332
- language: French
  speakers: 312
- language: Bengali
  speakers: 278
- language: Portuguese
  speakers: 264
