# Population in millions, 2023
- continent: Asia
  region: Southern Asia
  people: 2030
- continent: Asia
  region: Eastern Asia
  people: 1660
- continent: Asia
  region: South-East Asia
  people: 690
- continent: Asia
  region: Western Asia
  people: 300
- continent: Africa
  region: Eastern Africa
  people: 480
- continent: Africa
  region: Western Africa
  people: 440
- continent: Africa
  region: Northern Africa
  people: 260
- continent: Africa
  region: Central Africa
  people: 200
- continent: Europe
  region: Eastern Europe
  people: 290
- continent: Europe
  region: Western Europe
  people: 200
- continent: Europe
  region: Southern Europe
  people: 150
- continent: Americas
  region: South America
  people: 440
- continent: Americas
  region: North America
  people: 380
- continent: Americas
  region: Central America
  people: 185
- continent: Oceania
  region: Australia and New Zealand
  people: 32
