<?php

  // What each test is for - the descriptions the overview tables show. Kept apart from
  // the pages themselves, because a page is fetched and compared byte for byte: a comment
  // added to one to describe it changes what it renders.

  function getSuiteWhatList () {

    return [

      'index'                     => 'The one test fetched without padInclude: the _common wrapper, padOpen and padClose with the menu, and the title shown through showTitle',
      'menu'                      => 'The {menu} include - lines.pad around it, menu.json behind it, a link per application',
      'reference'                 => 'The _common _lib helpers a page calls directly - getReference() over the type handlers, and the Xref link builders',
      'misc/db'                   => 'The demo database through the credentials _common supplies - the one test that queries it',
      'regression/errors/error/index'   => 'The menu of the pages that end a request; each of those is a test of its own',
      'error/throw'               => 'The {exception} tag, which throws a real PHP exception from the template',
      'error/exit'                => 'The {exit} tag, which ends the request where it stands - and ships nothing at all, which the pattern pins',
      'error/dump'                => 'The {dump} tag, which stops the request on the engine state dump',
      'misc/trace'                => 'The {trace} tag wrapping a scope in the execution trace',
      'misc/react'                => 'The {reactData} tag over a static provider, and the @providers reference reading the parked result back',
      'select/support/prefix'     => 'The select: prefix spelling of a declared table, which also says the word the reference matcher looks for',
      'select/demo/options'       => 'Every option a declared table takes on the tag - where, order, fields, group, having, rollup, distinctrow, db and union - one labelled line each over the staff table',
      'catalog/tags'              => 'One line per built-in tag no other page reaches - the catalogue half of the reference coverage',
      'catalog/prefixes'          => 'One line per type prefix, each in its literal spelling',
      'catalog/properties'        => 'Every property and @ reference form on one page',
      'catalog/options'           => 'One line per tag option, including the ones that assert being inert',
      'catalog/functions'         => 'One line per pipe function over a stated value',
      'catalog/handling'          => 'The data handling options, each over a list whose answer is obvious',
      'catalog/volatile'          => 'The two draws - {ajax} ids and now - pinned by shape in one regex',
      'catalog/common'            => 'The common: prefix reaching the shared application by name - the one catalogue line that needs _common',
      'request/post'              => 'A real POST through padCurl - the fields travel in the body and arrive as page globals',
      'request/rawbody'           => 'A request body that is no form, posted as text/plain and read back through php://input',
      'request/cookie'            => 'A cookie sent with the request, read from $_COOKIE by the fixture',
      'request/redirect'          => 'A redirecting page, seen unfollowed - status and destination - and followed to where it lands',
      'request/vars'              => 'The intake fixture bare: no request vars, so the defaults show',
      'request/body'              => 'The raw-body fixture bare: an empty php://input',
      'request/jar'               => 'The cookie fixture bare: an empty jar',
      'request/session'           => 'A page fetching another shares its session - the fixture answers with this very request-s id',
      'request/upload'            => 'A multipart upload: the payload arrives with its name, size and PHP-s word that it was uploaded',
      'request/todo'              => 'A whole action round-trip: post a marker through todoPost, see it land, restore the store',
      'request/ses'               => 'The session fixture bare: some id, pinned by shape',
      'request/up'                => 'The upload fixture bare: no file',
      'callback'                  => 'The row phase of a streaming callback, which reads the occurrence fields as plain variables',
      'globals'                   => 'object: over a page variable, which in a request is a global like any other',
      'pairing'                   => 'A page pair: the .php half fills in what the .pad half prints',
      'phponly'                   => 'A page with no template at all - what its .php echoes is the page',
      'htmlpage'                  => 'An .html file as the template half of a pair - variables, pipes, a loop and a property all resolve in it',
      'htmlboth'                  => 'A page with both a .pad and an .html - the .pad wins',
      'htmlonly'                  => 'An .html page with no .php half, carrying a tag of its own',
      'db/array'                  => 'The db() array command through a page variable, and the else branch when nothing matches',
      'db/array2'                 => 'The same through the {array} tag, which hands its parameter to db() as the command word',
      'db/check'                  => 'The db() check command, which answers whether a row exists rather than returning one',
      'db/check2'                 => 'The same through the {check} tag',
      'db/field'                  => 'The db() field command, which returns one value',
      'db/field2'                 => 'The same through the {field} tag',
      'db/record'                 => 'The db() record command, which returns one row',
      'db/record2'                => 'The same through the {record} tag',
      'deep/index'                => 'A page rendering a page rendering a page, each level with its own _lib and _include',
      'handlers/index'            => 'The menu of the handler family; each of those is a test of its own',
      'handlers/error_1'          => 'An engine-raised PHP warning from a tag - an undefined variable - which $padErrorLevel promotes to an ended request',
      'handlers/error_2'          => 'The same engine-raised warning from the page rather than from a tag',
      'handlers/exception_1'      => 'An uncaught PHP exception from a tag',
      'handlers/exception_2'      => 'An uncaught PHP exception from a page',
      'handlers/pad_1'            => 'The {error} tag, which ends the request from the template',
      'handlers/pad_2'            => 'The same failure raised from the page',
      'handlers/shutdown_1'       => 'A fatal error, which the shutdown handler catches rather than the error handler',
      'handlers/shutdown_2'       => 'The same from a page',
      'handlers/warning_1'        => 'A PHP warning, which $padErrorLevel promotes to an ended request',
      'handlers/warning_2'        => 'The same from a page',
      'file/file'                 => 'The {file} tag writing four files, with date, stamp and id naming them',
      'file/done'                 => 'The page a file-output request lands on, reporting the name it was handed',
      'file/index'                => 'Output type file: the page is written to disk and the request restarts on file/done',
      'functions/date'            => 'The date function over a timestamp, a format and a strtotime modifier',
      'hello/index'               => 'The smallest page pair there is, and the one redirect and restart land on',
      'misc/eval'                 => 'The evaluator over the forms the manual shows - precedence, the @ placeholder, pipes',
      'misc/local'                => 'Reading a file from _data/ by name, in each format padData() accepts',
      'misc/parms'                => 'Parameters, options and variables on a tag, over a PHP array, a constant and a store',
      'misc/datatypes'            => 'The html and range data types: a tidied document walked to its values, and both range spellings',
      'manual/3_ways_to_make_a_table' => 'The start, end and else constructs over one table',
      'manual/doc3'               => 'Tag properties read through a content store',
      'manual/name'               => 'How PAD names a tag, and the name option that overrides it',
      'manual/table_fun'          => 'Ten ways of showing one table, each embedding one of the tableFun pages',
      'manual/variable_kinds'     => 'The variable prefixes, as far as the manual page got',
      'manual/z99'                => 'A page whose .php returns a string, which the build prepends to the page',
      'select/demo/join'          => 'The select subsystem walking a declared relation - a join written as nesting',
      'select/demo/union'         => 'A select table declared over a union of several tables',
      'select/support/test'       => 'A select table with a relation, read by id',
      'select/support/topic'      => 'A content store merged into a select result through @content@',
      'select/support/json'       => 'A note rather than a test - see _cases/README.md. It does exercise htmlAttrJson',
      'tags/redirect'             => 'The {redirect} tag, and the variable it hands the page it lands on',
      'tags/restart'              => 'The {restart} tag, which re-runs the request on another page carrying a variable',
      'tags/script'               => 'The script: prefix running a shell, python, perl and php script from _scripts/',
      'vars/at/1'                 => 'The @ reference over a flat global and a nested one, by name and by wildcard',
      'vars/at/2'                 => 'The same references where the value is buried five levels deep',
      'vars/at/7'                 => 'The @ reference walking an XML file, with optional hiding what is not there',
      'vars/at/8'                 => 'A dotted path with a condition at each step, into a data file',
      'vars/at/9'                 => 'The @ reference as a tag pair and through the {at} tag, over the same data',
      'vars/at/random'            => 'The wildcard forms of a dotted reference, each drawn fresh, asserted by shape',
      'start/index'               => 'Everything under start/ at once - the code, page and combi chains, nested and hello',
      'start/hello'               => 'One page rendered eight times through {page}, each option with a colour to tell it apart',
      'start/nested'              => 'A {page} inside a {page}, the shortest form of the chains beside it',
      'start/code/index'          => 'The eight {code} variants side by side',
      'start/page/index'          => 'The eight {page} chains side by side, which is what makes their differences readable',
      'start/combi/index'         => 'The three combi chains together',
      'start/combi1/index'        => 'A {page} chain mixing the options rather than using one throughout',
      'start/combi2/index'        => 'Another mixture of them',
      'start/combi3/index'        => 'A third mixture',
      'start/page/1/index'        => 'Nine nested {page} calls setting a variable - with no option it leaks outward',
      'start/page/2/index'        => 'The same chain with sandbox, so each pass has its own scope and the value unwinds',
      'start/page/3/index'        => 'The same chain with reset',
      'start/page/4/index'        => 'The same chain with clean',
      'start/page/5/index'        => 'The same chain incrementing rather than setting, with no option',
      'start/page/6/index'        => 'Incrementing with sandbox',
      'start/page/7/index'        => 'Incrementing with reset',
      'start/page/8/index'        => 'Incrementing with clean',
      'start/code/set/base'       => 'Nine nested {code} passes, each one setting the variable',
      'start/code/set/reset'      => 'Nine nested {code} passes, each one setting the variable, with reset',
      'start/code/set/clean'      => 'Nine nested {code} passes, each one setting the variable, with clean',
      'start/code/set/sandbox'    => 'Nine nested {code} passes, each one setting the variable, with sandbox',
      'start/code/increment/base' => 'Nine nested {code} passes, each one incrementting the variable',
      'start/code/increment/reset' => 'Nine nested {code} passes, each one incrementting the variable, with reset',
      'start/code/increment/clean' => 'Nine nested {code} passes, each one incrementting the variable, with clean',
      'start/code/increment/sandbox' => 'Nine nested {code} passes, each one incrementting the variable, with sandbox',
      'tableFun/fun_1_a'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_1_b'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_2_a'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_3_a'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_3_b'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_5_a'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_5_b'          => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_8'            => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_9'            => 'One of the ten ways of showing the same table, embedded by manual/table_fun',
      'tableFun/fun_0'            => 'The {content} definition the other nine print their cells through - it renders nothing itself',

    ];

  }

?>
