; PAD templates - highlights for Helix: queries/highlights.scm in Helix's capture names,
; written by editors/generate.php - do not edit by hand.

(comment) @comment

(construct) @keyword.directive

[
  "{"
  "}"
  "~"
] @punctuation.special

(close_tag
  "/" @punctuation.special)

(variable) @variable

(placeholder) @variable.builtin

(string) @string

(number) @constant.numeric

(format) @string.special

(operator) @operator

[
  "|"
  "="
] @operator

[
  "("
  ")"
  "["
  "]"
] @punctuation.bracket

[
  ","
  ":"
] @punctuation.delimiter

(prefix) @namespace

(property) @variable.other.member

(option_name) @attribute

(tag_name
  target: (identifier) @tag)

(property_reference
  target: (identifier) @tag)

(prefixed_name
  name: (identifier) @function)

; ---- generated by editors/generate.php from pad/ - do not edit by hand ----

(tag_name
  name: (identifier) @keyword
  (#any-of? @keyword
    "accordion" "action" "ajax" "array" "assert" "asset" "at" "attrs"
    "auth" "avatar" "barcode" "block" "bool" "branch" "break" "cache"
    "calendar" "can" "cannot" "carousel" "case" "cease" "chart" "check"
    "chess" "classes" "close" "code" "collection" "content" "continue" "count"
    "crossword" "csrf" "curl" "data" "debug" "decrement" "diff" "dir"
    "dump" "echo" "else" "elseif" "error" "exception" "excerpt" "exists"
    "exit" "extends" "false" "feature" "field" "file" "files" "flag"
    "flash" "flush" "foo" "form" "fragment" "get" "gravatar" "guest"
    "highlight" "icon" "identicon" "if" "ifchanged" "ignore" "increment" "input"
    "keep" "live" "lorem" "mail" "make" "markdown" "meta" "modal"
    "nonce" "null" "open" "output" "pad" "page" "pager" "parent"
    "parms" "placeholder" "progress" "pull" "push" "qr" "rating" "reactData"
    "record" "recurse" "redirect" "remove" "restart" "resume" "sandbox" "sequence"
    "set" "sitemap" "slot" "spaceless" "sparkline" "stack" "sudoku" "switch"
    "tab" "tabs" "textarea" "tidy" "trace" "trans" "tree" "true"
    "until" "when" "while"))

(tag_name
  name: (identifier) @tag
  (#not-any-of? @tag
    "accordion" "action" "ajax" "array" "assert" "asset" "at" "attrs"
    "auth" "avatar" "barcode" "block" "bool" "branch" "break" "cache"
    "calendar" "can" "cannot" "carousel" "case" "cease" "chart" "check"
    "chess" "classes" "close" "code" "collection" "content" "continue" "count"
    "crossword" "csrf" "curl" "data" "debug" "decrement" "diff" "dir"
    "dump" "echo" "else" "elseif" "error" "exception" "excerpt" "exists"
    "exit" "extends" "false" "feature" "field" "file" "files" "flag"
    "flash" "flush" "foo" "form" "fragment" "get" "gravatar" "guest"
    "highlight" "icon" "identicon" "if" "ifchanged" "ignore" "increment" "input"
    "keep" "live" "lorem" "mail" "make" "markdown" "meta" "modal"
    "nonce" "null" "open" "output" "pad" "page" "pager" "parent"
    "parms" "placeholder" "progress" "pull" "push" "qr" "rating" "reactData"
    "record" "recurse" "redirect" "remove" "restart" "resume" "sandbox" "sequence"
    "set" "sitemap" "slot" "spaceless" "sparkline" "stack" "sudoku" "switch"
    "tab" "tabs" "textarea" "tidy" "trace" "trans" "tree" "true"
    "until" "when" "while"))

((function_name) @function.builtin
  (#any-of? @function.builtin
    "abbreviate" "after" "afterLast" "ago" "before" "beforeLast" "between" "bold"
    "bytes" "capitalize" "close" "contains" "currency" "cut" "date" "default"
    "encodeHigh" "escape" "exists" "highlight" "html" "ignore" "in" "left"
    "like" "localDate" "lookup" "lower" "markdown" "matches" "max_len" "mid"
    "nbsp" "now" "open" "optional" "ordinal" "range" "replace" "right"
    "sanitize" "slashes" "slug" "stripLow" "stripslashes" "substr" "tag" "time"
    "timestamp" "trans" "trim" "truncate" "ucwords" "upper" "url" "white"))

((function_name) @function
  (#not-any-of? @function
    "abbreviate" "after" "afterLast" "ago" "before" "beforeLast" "between" "bold"
    "bytes" "capitalize" "close" "contains" "currency" "cut" "date" "default"
    "encodeHigh" "escape" "exists" "highlight" "html" "ignore" "in" "left"
    "like" "localDate" "lookup" "lower" "markdown" "matches" "max_len" "mid"
    "nbsp" "now" "open" "optional" "ordinal" "range" "replace" "right"
    "sanitize" "slashes" "slug" "stripLow" "stripslashes" "substr" "tag" "time"
    "timestamp" "trans" "trim" "truncate" "ucwords" "upper" "url" "white"))

(arguments
  (identifier) @attribute
  (#any-of? @attribute
    "atLeastOnce" "avg" "before" "bool" "both" "cache" "callback" "close"
    "content" "data" "dedup" "demand" "dump" "duplicates" "else" "end"
    "error" "first" "glue" "group" "ignore" "last" "left" "max"
    "merge" "min" "negative" "noError" "notOk" "null" "open" "optional"
    "orderly" "page" "parent" "pre" "print" "quote" "random" "reverse"
    "right" "row" "rows" "shuffle" "slice" "sort" "splice" "start"
    "sum" "tidy" "toBool" "toContent" "toData" "trace" "track" "trim"
    "where"))

(arguments
  (identifier) @keyword.operator
  (#any-of? @keyword.operator
    "eq" "ne" "gt" "lt" "ge" "le" "and" "or"
    "xor" "not" "range"))

; ---- end of generated ----
