#!/usr/bin/env php
<?php

  if     ( $padOS == 'lin' ) $padHome = '/home/herbert/pad';
  elseif ( $padOS == 'dar' ) $padHome = '/Users/herbert/pad';
  elseif ( $padOS == 'win' ) $padHome = '/pad';
  else                       die ( "Unsuported OS: $padOS" );

  $padApp  = 'cli';
  $padApps = "$padHome/apps/";
  $padData = "$padHome/DATA/";
  
  include "$padHome/pad/pad.php";

?>